-- ADMIN COMPLET — Malagasy Events
-- À exécuter dans Supabase : SQL Editor → New query → coller → Run

-- Fonction : est-ce l'admin officiel ?
create or replace function public.is_admin() returns boolean
language sql stable security definer as $$
  select exists(select 1 from public.profiles where id = auth.uid() and username = 'Malagasy_events_admin');
$$;

-- ── TABLE EVENTS ──
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null, date text not null, location text default '', city text default '',
  category text default 'Autre', image text default '', price text default '',
  organizer text default '', "ticketUrl" text default '', description text default '',
  "mediaUrls" jsonb default '[]', "createdAt" text default ''
);
alter table public.events enable row level security;
drop policy if exists "events lecture publique" on public.events;
create policy "events lecture publique" on public.events for select using (true);
drop policy if exists "events admin insert" on public.events;
create policy "events admin insert" on public.events for insert with check (public.is_admin());
drop policy if exists "events admin update" on public.events;
create policy "events admin update" on public.events for update using (public.is_admin());
drop policy if exists "events admin delete" on public.events;
create policy "events admin delete" on public.events for delete using (public.is_admin());

-- ── TABLE GASTRO ──
create table if not exists public.gastro (
  id bigint generated by default as identity primary key,
  name text not null, type text default 'Traiteur', region text default '', note text default '',
  fb text default '', insta text default '', tiktok text default '', contact text default '',
  city text default '', address text default '', phone text default '',
  lat double precision, lng double precision
);
alter table public.gastro enable row level security;
drop policy if exists "gastro lecture publique" on public.gastro;
create policy "gastro lecture publique" on public.gastro for select using (true);
drop policy if exists "gastro admin insert" on public.gastro;
create policy "gastro admin insert" on public.gastro for insert with check (public.is_admin());
drop policy if exists "gastro admin update" on public.gastro;
create policy "gastro admin update" on public.gastro for update using (public.is_admin());
drop policy if exists "gastro admin delete" on public.gastro;
create policy "gastro admin delete" on public.gastro for delete using (public.is_admin());

-- ── TABLE VIDEOS ──
create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  type text default 'aftermovie', title text not null, "youtubeUrl" text default '',
  thumbnail text default '', "eventName" text default '', "eventId" bigint,
  date text default '', city text default '', description text default '',
  "isTeaser" boolean default false, views int default 0
);
alter table public.videos enable row level security;
drop policy if exists "videos lecture publique" on public.videos;
create policy "videos lecture publique" on public.videos for select using (true);
drop policy if exists "videos admin insert" on public.videos;
create policy "videos admin insert" on public.videos for insert with check (public.is_admin());
drop policy if exists "videos admin update" on public.videos;
create policy "videos admin update" on public.videos for update using (public.is_admin());
drop policy if exists "videos admin delete" on public.videos;
create policy "videos admin delete" on public.videos for delete using (public.is_admin());

-- ── DONNÉES ACTUELLES ──
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (1,'Soirée Malagasy Paris','2026-07-12','Paris 11ème','Paris','Soirée','/posters/soiree-malagasy-paris.svg','15€','Mafana Vibes','https://helloasso.com','Une soirée inoubliable au cœur de Paris pour célébrer la culture malagasy. DJ, danses traditionnelles, cocktails et ambiance chaleureuse garantis !','[]'::jsonb,'2026-07-13T19:15:38.489Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (2,'Hira Gasy Île-de-France','2026-07-20','Créteil','Paris','Culture','https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400','10€','Association Soa','','Le Hira Gasy est l''art oratoire traditionnel de Madagascar. Venez découvrir chants, poésies et sagesses ancestrales portés par des artistes passionnés.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (3,'Repas Communautaire Malagasy','2025-03-10','Lyon','Lyon','Gastronomie','https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400','Gratuit','Malagasy Lyon','','Retrouvez la communauté malagasy de Lyon autour de plats traditionnels : romazava, ravitoto, lasopy... Un moment de partage et de convivialité.','["https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400","https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400"]'::jsonb,'2025-03-01T00:00:00.000Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (4,'Princio & Njara Marcel — Revy Revy Vacances','2026-07-18','Florida Palace','Marseille','Soirée','https://madatsara.com/uploads/medias/image-6a4c8d808767b.jpg','30€ prévente / 35€ sur place','Revy Revy Vacances','https://www.facebook.com/photo/?fbid=122106136563370277&set=pcb.122106136827370277','Princio et Njara Marcel en live au Florida Palace de Marseille ! Revy Revy Vacances — ambiance gasy garantie. À partir de 21h.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (5,'Que Calor — 206 Vibes, Kosmo, Midnight 261, Falfa','2026-07-24','Que Calor Paris','Paris','Soirée','/posters/que-calor.svg','','Que Calor Paris','','Soirée Que Calor à Paris avec 206 Vibes, Kosmo, Midnight 261 et Falfa aux platines. Horaire à confirmer — suivez l''Instagram de Que Calor Paris.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (6,'Princio & Njara Marcel — Revy Revy Vacances','2026-07-24','Salle climatisée Xeraco','Toulouse','Soirée','/posters/revy-toulouse.svg','','Revy Revy Vacances','','Princio et Njara Marcel en live à Toulouse, salle climatisée Xeraco. Revy Revy Vacances — à partir de 21h.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (7,'Princio & Njara Marcel — Samedi joli faradoboka','2026-07-25','Sport Indoor, 8 av. de Scandinavie, Les Ulis (91)','Paris','Soirée','https://madatsara.com/uploads/medias/image-6a4c8d40a13da.jpg','30€ prévente / 35€ sur place','Revy Revy Vacances','https://urls.fr/u2coVC','Princio et Njara Marcel en live aux Ulis pour clôturer la tournée Revy Revy Vacances en Île-de-France. À partir de 21h.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (8,'Dîner solidaire malgache — Bodo & Fenoamby','2026-07-11','Espace Dan Ar Braz, Quimper','Quimper','Gastronomie','https://madatsara.com/uploads/medias/image-69ebc57377ff6.jpg','25€ / 15€ enfant','Une Ruche Un Enfant','https://madatsara.com/evenement_diner-solidaire-malgache-avec-bodo-fenoamby-espace-dan-ar-braz-quimper.html','Dîner solidaire malgache animé par Bodo, Fenoamby et DJ Colonel à Quimper, dès 19h30. Au profit de l''installation d''un forage à Andranomaintso. 20€ à emporter, tombola sur place.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (9,'Nono — Grand spectacle d''été (1ère édition)','2026-07-13','Domaine de la Beauvoisière, Avrainville (91)','Paris','Soirée','https://madatsara.com/uploads/medias/image-6a28834de4129.jpg','','Mada Mifety','https://madatsara.com/evenement_nonoh-grand-spectacle-dete-1ere-edition-domaine-de-beauvoisiere-avrainville.html','Mada Mifety présente Nono pour la 1ère édition du Grand spectacle d''été au Domaine de la Beauvoisière (Avrainville, 91). Début 21h30, after ambiance DJ rétro, tombola Paris–Tana–Paris.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (10,'Hajazz en cabaret','2026-08-13','La Grande Rouge, La Chapelle-Naude (71)','La Chapelle-Naude','Soirée','https://madatsara.com/uploads/medias/image-6a4fe73f740d4.jpg','8€ / gratuit -12 ans','La Grande Rouge','https://www.helloasso.com/associations/association-la-petite-mandarine/evenements/hajazz-13-aout-grange-rouge','Hajazz en solo à La Grande Rouge (Saône-et-Loire). Buvette/restauration dès 18h, concert 20h, jam session 21h–minuit avec les amis musiciens.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (11,'Shao Boana en showcase','2026-08-15','La Lagune, base de loisirs, Jonzac (17)','Jonzac','Soirée','https://madatsara.com/uploads/medias/Shao-Boana-Showcase-La-Lagune-base-de-loisirs-Jonzac-69bab805a4d96.jpg','','La Lagune','https://madatsara.com/evenement_shao-boana-showcase-la-lagune-base-de-loisirs-jonzac.html','Shao Boana « Madagascar Vibes » en sound system à La Lagune de Jonzac (17). Roots reggae & dancehall riddims, dès 20h30.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (12,'Feo Gasy en concert','2026-09-04','Maison pour tous Melina Mercouri, Montpellier','Montpellier','Culture','https://madatsara.com/uploads/medias/image-6a4d5ab6d0a00.jpg','30€','Maison pour tous Melina Mercouri','https://madatsara.com/evenement_feo-gasy-en-concert-maison-pour-tous-melina-mercouri-montpellier.html','Le groupe Feo Gasy en concert « Any indray andro… » à la Maison pour tous Melina Mercouri (64 route de Lavérune, Montpellier), vendredi 4 septembre à 20h30.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (13,'Rija Ramanantoanina en concert','2026-10-17','Espace Magnan, Nice','Nice','Culture','https://madatsara.com/uploads/medias/image-6a52334735617.jpg','20€ / 30€','Espace Magnan','https://madatsara.com/evenement_rija-ramanantoanina-concert-espace-magnan-nice.html','Rija Ramanantoanina en concert à l''Espace Magnan de Nice — musique malgache & jazz, nouvel album « FY ». 19h30, restauration malgache dès 18h30.','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (14,'Soirée d''intégration GS Lille 2026-2027','2026-10-17','Lille','Lille','Soirée','','','Gasy Sport Lille','https://www.facebook.com/gslille','📌 Date estimée — à confirmer par l''organisateur. La soirée de rentrée de l''association sportive et culturelle malgache de Lille, chaque mi-octobre (éditions 2023 et 2024 confirmées).','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (15,'Tournoi de la Solidarité — CSM','2026-10-31','Centre sportif Saint-Exupéry, Villebon-sur-Yvette (91)','Paris','Sport','','','Collectif Sport Malagasy','https://www.facebook.com/profile.php?id=100064795630232','📌 Date estimée — à confirmer par l''organisateur. Le grand tournoi foot & basket de la diaspora, chaque week-end de la Toussaint à Villebon-sur-Yvette (éditions 2024 et 2025 au même endroit).','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (16,'Tournoi de Noël — Ligue Clichy Madagascar','2026-11-28','Clichy / Paris','Paris','Sport','','','Ligue Clichy Madagascar','https://www.facebook.com/profile.php?id=100063642368550','📌 Date estimée — à confirmer par l''organisateur. Le tournoi de basket de fin d''année de la ligue malgache de Clichy (édition 2025 : 29 nov et 28 déc).','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;
insert into public.events (id,title,date,location,city,category,image,price,organizer,"ticketUrl",description,"mediaUrls","createdAt") values (17,'Madadiaspora Foot — RNS','2026-12-19','Stade Robinson, Corbeil-Essonnes (91)','Paris','Sport','','','RNS - CEN','https://www.facebook.com/rns.cen','📌 Date estimée — à confirmer par l''organisateur. Le tournoi de foot d''hiver de la RNS au stade Robinson de Corbeil-Essonnes (édition 2025 : 20 déc).','[]'::jsonb,'2026-07-13T19:15:38.526Z') on conflict (id) do nothing;

insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (1,'Ikala Kara','Restaurant','Provence-Alpes-Côte d''Azur','Restaurant malgache & karaoké, quartier La Plaine','https://www.facebook.com/Ikalakara','','','','Marseille','La Plaine, Marseille','',43.2938,5.3828) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (2,'O''Bol d''Or','Restaurant','','Restaurant — spécialités asiatiques & malgaches','https://www.facebook.com/profile.php?id=61558005182008','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (3,'Le Tana','Restaurant','Provence-Alpes-Côte d''Azur','Cuisine malgache & océan Indien — ouvert du mardi au samedi','https://www.facebook.com/restaurantletana','','','','Le Tholonet (13)','283 avenue Paul Roubaud, Palette, 13100 Le Tholonet','',43.5124,5.488) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (4,'Chez Maman Mada','Restaurant','','','','https://www.instagram.com/chezmaman_mada','https://www.tiktok.com/@chezmamantt','Zo Rav. (propriétaire)','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (5,'La Gourmandise Malgache','Traiteur','','','https://www.facebook.com/profile.php?id=100076189512327','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (6,'Pili Pili Malgache Food','Traiteur','','Recettes traditionnelles de Madagascar pour vos événements','https://www.facebook.com/pilipilimalgachefood','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (7,'Chez Daben','Traiteur','','Traiteur malgache','https://www.facebook.com/profile.php?id=100067003274574','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (8,'Traiteur Franco-Malagasy Paris','Traiteur','Île-de-France','Mariages & événements','https://www.facebook.com/wenddingtraiteurmalagasy','','','','Paris','','+33 6 35 97 42 34',48.8566,2.3522) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (9,'Chez Tiana','Traiteur','','Ravitoto & mofo gasy faits maison, salé et sucré','https://www.facebook.com/Cheztiana','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (10,'Naffees Traiteur','Traiteur','','Spécialités indo-pakistanaises & malgaches, halal','https://www.facebook.com/traiteurevenementielnaffees','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (11,'Nini + Vous','Traiteur','Nouvelle-Aquitaine','Chef à domicile, traiteur, livraison — cuisine franco-malgache','https://www.facebook.com/profile.php?id=100086724786890','','','','Bordeaux','Bordeaux et sa région','',44.8378,-0.5792) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (12,'La Cuisine de Gabriel','Traiteur','','','https://www.facebook.com/lacuisinedegabriel','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (13,'Malak Traiteur','Traiteur','','','https://www.facebook.com/profile.php?id=100064014279221','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (14,'Au Soleil de Madagascar','Food truck','','Food truck & traiteur','https://www.facebook.com/AuSoleildeMadagascar','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (15,'Harena Sisters','Traiteur','','','https://www.facebook.com/HarenaSistersTraiteur','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (16,'Cuisine Malgache et d''ailleurs','Traiteur','','Communauté de recettes malgaches et du monde','https://www.facebook.com/EvitraAkohoFaMahaOmby','','','','','','',null,null) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (17,'Le Rendez-vous Franco-Malgache','Restaurant','Provence-Alpes-Côte d''Azur','Cuisine traditionnelle franco-malgache, produits frais','https://www.facebook.com/profile.php?id=100092651710205','','','','L''Isle-sur-la-Sorgue (84)','L''Isle-sur-la-Sorgue, Vaucluse','+33 7 88 95 46 67',43.9195,5.0512) on conflict (id) do nothing;
insert into public.gastro (id,name,type,region,note,fb,insta,tiktok,contact,city,address,phone,lat,lng) values (18,'Sakafo Street','Food truck','','','','https://www.instagram.com/sakafostreet','','Tojo A. (gérant)','','','',null,null) on conflict (id) do nothing;

insert into public.videos (id,type,title,"youtubeUrl",thumbnail,"eventName","eventId",date,city,description,"isTeaser",views) values (1,'aftermovie','After-movie — Repas Communautaire Lyon 2025','https://www.youtube.com/embed/dQw4w9WgXcQ','https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400','Repas Communautaire Malagasy',3,'2025-03-10','Lyon','Revivez la magie du repas communautaire de Lyon.',false,1240) on conflict (id) do nothing;
insert into public.videos (id,type,title,"youtubeUrl",thumbnail,"eventName","eventId",date,city,description,"isTeaser",views) values (2,'aftermovie','Teaser — Soirée Malagasy Paris','https://www.youtube.com/embed/dQw4w9WgXcQ','https://images.unsplash.com/photo-1533317480453-7a4b6ad0a174?w=400','Soirée Malagasy Paris',1,'2026-07-12','Paris','Le teaser de la soirée la plus attendue de l''été !',true,856) on conflict (id) do nothing;
insert into public.videos (id,type,title,"youtubeUrl",thumbnail,"eventName","eventId",date,city,description,"isTeaser",views) values (3,'communaute','La communauté malagasy de Lyon se présente','https://www.youtube.com/embed/dQw4w9WgXcQ','https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400','',null,'2025-06-01','Lyon','Portrait de notre communauté.',false,432) on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.events','id'), greatest((select coalesce(max(id),1) from public.events),1));
select setval(pg_get_serial_sequence('public.gastro','id'), greatest((select coalesce(max(id),1) from public.gastro),1));
select setval(pg_get_serial_sequence('public.videos','id'), greatest((select coalesce(max(id),1) from public.videos),1));
