-- ════════════════════════════════════════════════════════════════
-- PUBLICATION DIRECTE ORGA + MEMBRE PREMIUM — Malagasy Events
-- À exécuter dans Supabase → SQL Editor → Run. Sans risque, idempotent.
-- ════════════════════════════════════════════════════════════════

-- 1. Les organisateurs publient leurs événements directement
alter table public.events add column if not exists owner_id uuid references public.profiles(id) on delete set null;

drop policy if exists "orga publie son evenement" on public.events;
create policy "orga publie son evenement" on public.events for insert
  with check (
    owner_id = auth.uid()
    and exists(select 1 from public.profiles where id = auth.uid() and plan = 'organisateur')
  );

drop policy if exists "orga modifie son evenement" on public.events;
create policy "orga modifie son evenement" on public.events for update
  using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "orga supprime son evenement" on public.events;
create policy "orga supprime son evenement" on public.events for delete
  using (auth.uid() = owner_id);

-- 2. Avantages partenaires (Membre Premium)
create table if not exists public.perks (
  id bigint generated by default as identity primary key,
  partner text not null,
  offer text not null,
  description text default '',
  code text default '',
  category text default 'Gastronomie',
  city text default '',
  active boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.perks enable row level security;

drop policy if exists "perks lecture publique" on public.perks;
create policy "perks lecture publique" on public.perks for select using (true);
drop policy if exists "perks admin insert" on public.perks;
create policy "perks admin insert" on public.perks for insert with check (public.is_admin());
drop policy if exists "perks admin update" on public.perks;
create policy "perks admin update" on public.perks for update using (public.is_admin());
drop policy if exists "perks admin delete" on public.perks;
create policy "perks admin delete" on public.perks for delete using (public.is_admin());

-- Exemples de structure (inactifs — active-les dans l'admin quand le partenariat est signé)
insert into public.perks (id,partner,offer,description,code,category,city,active) values
 (1,'Épicerie de Madagascar','-10% en boutique','Sur présentation du code Premium en caisse (exemple — partenariat à négocier).','PREMIUM10','Boutique','Paris 13e',false),
 (2,'Le Tana','Un café ou thé offert','Pour tout repas — sur présentation du code (exemple — partenariat à négocier).','PREMIUMTANA','Restaurant','Le Tholonet (13)',false),
 (3,'Boost billets','Accès prioritaire aux billets','Les événements partenaires réservent un quota de billets aux membres Premium pendant 24h.','','Événements','',false)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.perks','id'), greatest((select coalesce(max(id),1) from public.perks),1));
