-- ════════════════════════════════════════════════════════════════
-- LIEUX (Églises · Boutiques · Artisanat) — Malagasy Events
-- Annuaire par catégorie. À exécuter dans Supabase → SQL Editor → Run.
-- Sans risque, idempotent.
-- ════════════════════════════════════════════════════════════════

create table if not exists public.lieux (
  id bigint generated by default as identity primary key,
  category text not null default 'eglise',   -- 'eglise' | 'boutique' | 'artisanat'
  name text not null,
  denom text default '',                       -- sous-type : FJKM, FLM, Catholique…
  city text default '', address text default '',
  followers text default '', note text default '',
  fb text default '', insta text default '', site text default '', contact text default '',
  featured boolean not null default false
);
alter table public.lieux enable row level security;
drop policy if exists "lieux lecture publique" on public.lieux;
create policy "lieux lecture publique" on public.lieux for select using (true);
drop policy if exists "lieux admin insert" on public.lieux;
create policy "lieux admin insert" on public.lieux for insert with check (public.is_admin());
drop policy if exists "lieux admin update" on public.lieux;
create policy "lieux admin update" on public.lieux for update using (public.is_admin());
drop policy if exists "lieux admin delete" on public.lieux;
create policy "lieux admin delete" on public.lieux for delete using (public.is_admin());

-- ── ÉGLISES (14) ────────────────────────────────────────
insert into public.lieux (id,category,name,denom,city,address,followers,note,fb) values
 (1,'eglise','FJKM Wagner Finoana Paris','FJKM','Paris','7 bis rue Pasteur Wagner','2 000','Église protestante malgache','https://www.facebook.com/FJKM.WAGNER.FINOANA.PARIS'),
 (2,'eglise','Zanaka Ampielezana FJKM Ilanivato','FJKM','Paris','91 rue Blomet','501','Église protestante malgache','https://www.facebook.com/ZANAKAAMPIELEZANAFJKMILANIVATOATYANDAFY'),
 (3,'eglise','Voronkely Andiany Limohy FJKM Montrouge Renala','Jeunesse FJKM','Montrouge','','202','Organisation de jeunesse FJKM','https://www.facebook.com/profile.php?id=61561889865442'),
 (4,'eglise','FJKM Filadelfia Meaux Hetsika','FJKM','Meaux','','252','Église protestante malgache, billetterie événements','https://www.facebook.com/profile.php?id=61550865367217'),
 (5,'eglise','FJKM Betlehema Mifankatia Paris','FJKM','Noisy-le-Grand','','63','Église protestante malgache','https://www.facebook.com/profile.php?id=61575339845526'),
 (6,'eglise','FJKM Jerosalema Fitahiana Neuville','FJKM','Neuville-sur-Oise','','23','Église protestante malgache','https://www.facebook.com/profile.php?id=100077193282022'),
 (7,'eglise','FJKM Rennes Laval','FJKM','Rennes / Laval / Vannes / Lorient','','141','Communauté chrétienne protestante FJKM','https://www.facebook.com/profile.php?id=61583690953873'),
 (8,'eglise','VOMM FJKM Chartres','FJKM','Chartres','Hôtellerie Saint Yves','128','Culte à l''Hôtellerie Saint Yves',''),
 (9,'eglise','STK FJKM Filadelfia Meaux','Service FJKM','Meaux','','251','Service de proximité, billetterie concerts',''),
 (10,'eglise','FLM Paris','FLM','Paris','7 rue Marie Rose','','Église Luthérienne Malgache de Paris — Synode FLM Europe','https://www.facebook.com/flmparis'),
 (11,'eglise','FKMP — Fiangonana Katolika Malagasy eto Paris','Catholique','Paris / Île-de-France','','','Aumônerie Catholique Malgache de Paris et Île-de-France','https://www.facebook.com/KatolikaMalagasyEtoParisSyNyManodidina'),
 (12,'eglise','FJKM Montrouge-Paris Fiorenana','FJKM','Paris / Montrouge','','5 300','Membre du SPVFA SP37',''),
 (13,'eglise','FPMA Orléans','FPMA','Orléans','','1 100','Église Protestante Malgache en France — paroisse d''Orléans',''),
 (14,'eglise','Église Protestante Malgache (Pasteur Jacky)','Protestante','France','','990','Nouvelle église initiée par le Pasteur Jacky Randriambololona','')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.lieux','id'), greatest((select coalesce(max(id),1) from public.lieux),1));
