-- ════════════════════════════════════════════════════════════════
-- MESSAGERIE AVANCÉE — blocage, réglages de discussion, réactions
-- À exécuter dans Supabase → SQL Editor → Run. Sans risque, idempotent.
-- ════════════════════════════════════════════════════════════════

-- 1. Blocages entre membres
create table if not exists public.blocks (
  id bigint generated by default as identity primary key,
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
create unique index if not exists blocks_unique on public.blocks (blocker_id, blocked_id);
alter table public.blocks enable row level security;
drop policy if exists "voir ses blocages" on public.blocks;
create policy "voir ses blocages" on public.blocks for select using (auth.uid() in (blocker_id, blocked_id));
drop policy if exists "bloquer" on public.blocks;
create policy "bloquer" on public.blocks for insert with check (auth.uid() = blocker_id and blocker_id <> blocked_id);
drop policy if exists "debloquer" on public.blocks;
create policy "debloquer" on public.blocks for delete using (auth.uid() = blocker_id);

-- Un message ne peut pas être envoyé si l'un a bloqué l'autre
drop policy if exists "antiblocage messages" on public.messages;
create policy "antiblocage messages" on public.messages
  as restrictive for insert
  with check (not exists (
    select 1 from public.blocks b
    where (b.blocker_id = auth.uid() and b.blocked_id = recipient_id)
       or (b.blocker_id = recipient_id and b.blocked_id = auth.uid())
  ));

-- Supprimer une conversation : chaque participant peut supprimer les messages de ses convs
drop policy if exists "supprimer ses conversations" on public.messages;
create policy "supprimer ses conversations" on public.messages
  for delete using (auth.uid() = sender_id or auth.uid() = recipient_id);

-- 2. Réglages de discussion (couleur, icône) — propres à chaque membre
create table if not exists public.conv_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  other_id uuid not null references public.profiles(id) on delete cascade,
  color text default '',
  emoji text default '',
  unique (user_id, other_id)
);
alter table public.conv_settings enable row level security;
drop policy if exists "ses reglages" on public.conv_settings;
create policy "ses reglages" on public.conv_settings for select using (auth.uid() = user_id);
drop policy if exists "creer ses reglages" on public.conv_settings;
create policy "creer ses reglages" on public.conv_settings for insert with check (auth.uid() = user_id);
drop policy if exists "modifier ses reglages" on public.conv_settings;
create policy "modifier ses reglages" on public.conv_settings for update using (auth.uid() = user_id);

-- 3. Réactions sur les messages (1 par membre et par message)
create table if not exists public.message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  unique (message_id, user_id)
);
alter table public.message_reactions enable row level security;
drop policy if exists "reactions visibles par les participants" on public.message_reactions;
create policy "reactions visibles par les participants" on public.message_reactions
  for select using (exists (
    select 1 from public.messages m
    where m.id = message_id and auth.uid() in (m.sender_id, m.recipient_id)
  ));
drop policy if exists "reagir" on public.message_reactions;
create policy "reagir" on public.message_reactions
  for insert with check (
    auth.uid() = user_id
    and exists (select 1 from public.messages m where m.id = message_id and auth.uid() in (m.sender_id, m.recipient_id))
  );
drop policy if exists "modifier sa reaction" on public.message_reactions;
create policy "modifier sa reaction" on public.message_reactions for update using (auth.uid() = user_id);
drop policy if exists "retirer sa reaction" on public.message_reactions;
create policy "retirer sa reaction" on public.message_reactions for delete using (auth.uid() = user_id);
