-- ABONNEMENTS — garantie de fonctionnement (idempotent)
-- Crée la table si absente, applique les bonnes règles, évite les doublons.

create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
create unique index if not exists follows_unique on public.follows (follower_id, following_id);

alter table public.follows enable row level security;
drop policy if exists "follows lecture publique" on public.follows;
create policy "follows lecture publique" on public.follows for select using (true);
drop policy if exists "suivre" on public.follows;
create policy "suivre" on public.follows for insert with check (auth.uid() = follower_id and follower_id <> following_id);
drop policy if exists "ne plus suivre" on public.follows;
create policy "ne plus suivre" on public.follows for delete using (auth.uid() = follower_id);
