-- MALAGASY EVENTS — mise à niveau Trafic & Base sport
-- Peut être exécuté en une seule fois, même si les premières tables existent déjà.

create extension if not exists pgcrypto;

create table if not exists public.analytics_events (
  id bigint generated always as identity primary key,
  event_name text not null check(event_name in ('page_view','outbound_social_click','outbound_link_click')),
  page_path text not null default '/', page_title text not null default '', landing_path text not null default '',
  session_id uuid, visitor_id uuid, source text not null default 'direct', medium text not null default 'none',
  campaign text not null default '', content text not null default '', destination_host text not null default '',
  destination_url text not null default '', link_label text not null default '', platform text not null default '',
  device text, browser text, os text, created_at timestamptz not null default now()
);

alter table if exists public.analytics_events
  add column if not exists visitor_id uuid,
  add column if not exists device text,
  add column if not exists browser text,
  add column if not exists os text;

create index if not exists analytics_events_visitor_idx
on public.analytics_events(visitor_id,created_at desc);

create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);

alter table public.analytics_events enable row level security;
drop policy if exists "public append anonymous analytics" on public.analytics_events;
drop policy if exists "admins read analytics" on public.analytics_events;
create policy "public append anonymous analytics" on public.analytics_events
for insert to anon,authenticated with check(
  session_id is not null and visitor_id is not null
  and source !~* '(email|@|telephone|phone)'
  and campaign !~* '(email|@|telephone|phone)'
);
create policy "admins read analytics" on public.analytics_events
for select to authenticated using(public.is_admin());
grant insert on public.analytics_events to anon,authenticated;
grant select on public.analytics_events to authenticated;
grant usage,select on sequence public.analytics_events_id_seq to anon,authenticated;

comment on table public.analytics_events is
'Mesure interne pseudonyme réservée à Malagasy Events : aucun nom, e-mail, identifiant de compte ou adresse IP stocké.';

create or replace function public.purge_old_analytics_scheduled()
returns bigint language plpgsql security definer set search_path=public,pg_temp
as $$
declare deleted_count bigint;
begin
  delete from public.analytics_events where created_at < now()-interval '13 months';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end $$;
revoke all on function public.purge_old_analytics_scheduled() from public,anon,authenticated;

-- Nettoyage automatique chaque nuit à 03 h 17 UTC. Le bloc reste réexécutable.
create extension if not exists pg_cron with schema extensions;
do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname='mev-purge-old-analytics' limit 1;
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
  perform cron.schedule('mev-purge-old-analytics','17 3 * * *','select public.purge_old_analytics_scheduled();');
end $$;

create table if not exists public.sport_club_candidates (
  id bigint generated by default as identity primary key,
  name text not null unique,
  disciplines text[] not null default '{}',
  city text,
  instagram text,
  facebook text,
  source_name text,
  source_url text,
  verification_status text not null default 'a_verifier'
    check (verification_status in ('a_verifier','a_contacter','verifie')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sport_club_candidates enable row level security;
drop policy if exists "Base sport : gestion admin" on public.sport_club_candidates;
create policy "Base sport : gestion admin" on public.sport_club_candidates
for all to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

grant select,insert,update,delete on public.sport_club_candidates to authenticated;
grant usage,select on sequence public.sport_club_candidates_id_seq to authenticated;

insert into public.sport_club_candidates
  (name,disciplines,source_name,source_url,verification_status,notes)
values
  ('AS G.A.S','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Sport et compte social à confirmer.'),
  ('AEOM Toulouse',array['Volleyball'],'CEN / RNS','https://www.rns-cen.com/equipe-cen/','verifie','Citée comme représentante Volleyball par le CEN.'),
  ('AS Bezons','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Sport et compte social à confirmer.'),
  ('ASM Paris','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_contacter','Déjà dans l’annuaire ; disciplines précises à confirmer.'),
  ('ASMS Strasbourg','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Sport et compte social à confirmer.'),
  ('BOGASY FC',array['Football'],'CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_contacter','Compte officiel et ville à confirmer.'),
  ('E.F.A','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Nom complet et discipline à confirmer.'),
  ('Family Team','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Discipline à confirmer.'),
  ('Futsal Malagasy',array['Football','Futsal'],'CEN / RNS','https://www.rns-cen.com/equipe-cen/','verifie','Citée comme représentante Football par le CEN.'),
  ('MMVB','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Nom complet, ville et discipline à confirmer.'),
  ('Paris Gasyers','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Discipline à confirmer.'),
  ('PNG','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Nom complet et discipline à confirmer.'),
  ('PPG Kintana Gasy','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Discipline à confirmer.'),
  ('PPP13','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Ville et discipline à confirmer.'),
  ('Samy-Club','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Discipline à confirmer.'),
  ('Tsakarao','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Discipline à confirmer.'),
  ('Vétérans RNS','{}','CEN / RNS','https://www.rns-cen.com/equipe-cen/','a_verifier','Discipline à confirmer.')
on conflict (name) do update set
  disciplines=excluded.disciplines,
  source_name=excluded.source_name,
  source_url=excluded.source_url,
  notes=excluded.notes;
